name: PR Sanity Check

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Packages
        working-directory: ${{env.working-directory}}
        run: |
          npm install
      - name: Lint check
        working-directory: ${{env.working-directory}}
        run: |
          npm run lint